import { RawTranscriptItem, TranscriptSegment, NormalizedTranscript } from "@/types/transcript";
import { formatDuration } from "@/lib/utils";

/**
 * Decodes HTML entities commonly found in YouTube captions
 */
export function decodeHtmlEntities(str: string): string {
  if (!str) return "";
  return str
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&#x27;/g, "'")
    .replace(/&#x2F;/g, "/")
    .replace(/&nbsp;/g, " ")
    .replace(/&#(\d+);/g, (_, dec) => String.fromCharCode(dec));
}

/**
 * Normalizes raw transcript items from YouTube
 */
export function normalizeTranscript(
  rawItems: RawTranscriptItem[],
  videoId: string,
  languageCode: string = "en",
  languageName: string = "English",
  isAutoGenerated: boolean = false
): NormalizedTranscript {
  if (!rawItems || rawItems.length === 0) {
    return {
      videoId,
      language: languageCode,
      languageName,
      isAutoGenerated,
      totalSegments: 0,
      totalDurationSeconds: 0,
      totalWords: 0,
      segments: [],
      fullText: "",
      cleanText: "",
    };
  }

  const segments: TranscriptSegment[] = [];
  let prevText = "";

  rawItems.forEach((item, index) => {
    let text = decodeHtmlEntities(item.text || "")
      .replace(/\s+/g, " ")
      .replace(/\[Music\]/gi, "")
      .replace(/\[Applause\]/gi, "")
      .replace(/\[Laughter\]/gi, "")
      .trim();

    if (!text) return;

    // Remove exact duplicate consecutive fragments often sent by YouTube ASR
    if (text === prevText) return;

    // Compute offset in seconds (some libraries give milliseconds or seconds)
    const startTime = typeof item.offset === "number" ? (item.offset > 100000 ? item.offset / 1000 : item.offset) : 0;
    const duration = typeof item.duration === "number" ? (item.duration > 100000 ? item.duration / 1000 : item.duration) : 2.5;
    const endTime = startTime + duration;

    segments.push({
      index: segments.length + 1,
      startTime: Math.round(startTime * 100) / 100,
      duration: Math.round(duration * 100) / 100,
      endTime: Math.round(endTime * 100) / 100,
      startFormatted: formatDuration(startTime),
      endFormatted: formatDuration(endTime),
      text,
    });

    prevText = text;
  });

  const totalDurationSeconds = segments.length > 0 ? segments[segments.length - 1].endTime : 0;
  const fullText = segments.map((s) => s.text).join(" ");
  const totalWords = fullText.split(/\s+/).filter(Boolean).length;
  const cleanText = cleanPunctuationAndFillers(fullText);

  return {
    videoId,
    language: languageCode,
    languageName,
    isAutoGenerated,
    totalSegments: segments.length,
    totalDurationSeconds: Math.round(totalDurationSeconds),
    totalWords,
    segments,
    fullText,
    cleanText,
  };
}

/**
 * Creates clean script version without changing original meaning:
 * - Fixes capitalization at sentence starts
 * - Normalizes excessive punctuation
 * - Preserves every piece of spoken content
 */
export function cleanPunctuationAndFillers(text: string): string {
  if (!text) return "";

  let cleaned = text
    .replace(/\s+/g, " ")
    .replace(/(\s*,\s*){2,}/g, ", ")
    .replace(/(\s*\.\s*){2,}/g, ". ")
    .trim();

  // Capitalize sentence starts
  cleaned = cleaned.replace(/(^\s*|[.!?]\s+)([a-z])/g, (_, prefix, letter) => prefix + letter.toUpperCase());

  return cleaned;
}
