import { YouTubeVideoMetadata } from "@/types/youtube" ; 
import { NormalizedTranscript } from "@/types/transcript";

export interface ITranscriptProvider {
  getVideoMetadata(videoId: string): Promise<YouTubeVideoMetadata>;
  getTranscript(videoId: string, languageCode?: string): Promise<NormalizedTranscript>;
  getAvailableLanguages(videoId: string): Promise<Array<{ code: string; name: string; isAutoGenerated?: boolean }>>;
}

export interface ISpeechToTextProvider {
  transcribeAudio(audioUrlOrStream: string | Buffer, language?: string): Promise<NormalizedTranscript>;
}
