import { ITranscriptProvider } from "./types";
import { YouTubeVideoMetadata } from "@/types/youtube";
import { NormalizedTranscript, RawTranscriptItem, TranscriptErrorCode } from "@/types/transcript";
import { normalizeTranscript } from "./normalizer";
import { formatDuration } from "@/lib/utils";
import { YoutubeTranscript } from "youtube-transcript";

export class TranscriptError extends Error {
  code: TranscriptErrorCode;
  suggestion?: string;

  constructor(code: TranscriptErrorCode, message: string, suggestion?: string) {
    super(message);
    this.name = "TranscriptError";
    this.code = code;
    this.suggestion = suggestion;
  }
}

export class YouTubeTranscriptProvider implements ITranscriptProvider {
  /**
   * Fetch Video Metadata using YouTube oEmbed and Innertube API
   */
  async getVideoMetadata(videoId: string): Promise<YouTubeVideoMetadata> {
    const videoUrl = `https://www.youtube.com/watch?v=${videoId}`;
    const defaultThumbnail = `https://img.youtube.com/vi/${videoId}/maxresdefault.jpg`;

    let title = "YouTube Video";
    let channelName = "YouTube Creator";
    let channelUrl: string | undefined;
    let thumbnailUrl = defaultThumbnail;
    let durationSeconds = 0;

    // 1. Fetch official oEmbed data
    try {
      const oembedRes = await fetch(
        `https://www.youtube.com/oembed?url=${encodeURIComponent(videoUrl)}&format=json`,
        { headers: { "User-Agent": "Mozilla/5.0 (compatible; TubeMindBot/1.0)" } }
      );

      if (oembedRes.ok) {
        const oembed = await oembedRes.json();
        title = oembed.title || title;
        channelName = oembed.author_name || channelName;
        channelUrl = oembed.author_url;
        if (oembed.thumbnail_url) {
          thumbnailUrl = oembed.thumbnail_url;
        }
      }
    } catch (e) {
      // Fallback
    }

    // 2. Fetch Innertube video details (duration & verified title)
    try {
      const innertubeRes = await fetch("https://www.youtube.com/youtubei/v1/player", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
          "X-YouTube-Client-Name": "1",
          "X-YouTube-Client-Version": "2.20240313.01.00",
        },
        body: JSON.stringify({
          context: {
            client: {
              clientName: "WEB",
              clientVersion: "2.20240313.01.00",
              hl: "en",
              gl: "US",
            },
          },
          videoId,
        }),
      });

      if (innertubeRes.ok) {
        const data = await innertubeRes.json();
        if (data.videoDetails) {
          title = data.videoDetails.title || title;
          channelName = data.videoDetails.author || channelName;
          if (data.videoDetails.lengthSeconds) {
            durationSeconds = parseInt(data.videoDetails.lengthSeconds, 10) || 0;
          }
        }
      }
    } catch (e) {}

    return {
      videoId,
      url: videoUrl,
      title,
      channelName,
      channelUrl,
      durationSeconds,
      durationFormatted: formatDuration(durationSeconds),
      thumbnailUrl,
      hasCaptions: true,
      captionType: "auto",
      availableLanguages: [
        { code: "en", name: "English", isAutoGenerated: true },
        { code: "ur", name: "Urdu", isAutoGenerated: true },
        { code: "es", name: "Spanish", isAutoGenerated: true },
      ],
    };
  }

  async getAvailableLanguages(
    videoId: string
  ): Promise<Array<{ code: string; name: string; isAutoGenerated?: boolean }>> {
    return [
      { code: "en", name: "English", isAutoGenerated: true },
      { code: "ur", name: "Urdu", isAutoGenerated: true },
      { code: "es", name: "Spanish", isAutoGenerated: true },
      { code: "fr", name: "French", isAutoGenerated: true },
      { code: "de", name: "German", isAutoGenerated: true },
    ];
  }

  /**
   * Primary transcript retriever with robust multi-strategy fallback
   */
  async getTranscript(videoId: string, languageCode?: string): Promise<NormalizedTranscript> {
    let rawItems: RawTranscriptItem[] = [];
    let detectedLang = languageCode || "en";

    // Strategy 1: YoutubeTranscript fetch
    try {
      const config = languageCode ? { lang: languageCode } : undefined;
      const transcriptData = await YoutubeTranscript.fetchTranscript(videoId, config);

      if (transcriptData && transcriptData.length > 0) {
        rawItems = transcriptData.map((item) => ({
          text: item.text,
          duration: item.duration,
          offset: item.offset,
          lang: item.lang,
        }));
        if (transcriptData[0]?.lang) {
          detectedLang = transcriptData[0].lang;
        }
      }
    } catch (primaryErr: any) {
      // Strategy 2: If requested with a specific language that failed, try default language
      try {
        const transcriptData = await YoutubeTranscript.fetchTranscript(videoId);
        if (transcriptData && transcriptData.length > 0) {
          rawItems = transcriptData.map((item) => ({
            text: item.text,
            duration: item.duration,
            offset: item.offset,
            lang: item.lang,
          }));
          if (transcriptData[0]?.lang) {
            detectedLang = transcriptData[0].lang;
          }
        }
      } catch (fallbackErr: any) {
        const errStr = (primaryErr?.message || "") + " " + (fallbackErr?.message || "");

        if (errStr.includes("disabled") || errStr.includes("No captions")) {
          throw new TranscriptError(
            "CAPTIONS_DISABLED",
            "Transcripts or captions are disabled for this video by the creator.",
            "Try a video with closed captions or spoken audio enabled."
          );
        }

        if (errStr.includes("unavailable") || errStr.includes("Video unavailable")) {
          throw new TranscriptError(
            "VIDEO_NOT_FOUND",
            "This video could not be found or is private/deleted."
          );
        }

        throw new TranscriptError(
          "TRANSCRIPT_NOT_AVAILABLE",
          "Transcript is not available for this video.",
          "Check if the video has spoken audio or auto-generated captions enabled on YouTube."
        );
      }
    }

    if (!rawItems || rawItems.length === 0) {
      throw new TranscriptError(
        "TRANSCRIPT_NOT_AVAILABLE",
        "Transcript is not available for this video.",
        "The video might not contain spoken words or auto-captions haven't been generated yet."
      );
    }

    return normalizeTranscript(
      rawItems,
      videoId,
      detectedLang,
      this.getLanguageName(detectedLang),
      true
    );
  }

  private getLanguageName(code: string): string {
    const map: Record<string, string> = {
      en: "English",
      ur: "Urdu",
      es: "Spanish",
      fr: "French",
      de: "German",
      hi: "Hindi",
      ar: "Arabic",
      pt: "Portuguese",
      ja: "Japanese",
      zh: "Chinese",
    };
    return map[code.toLowerCase()] || code.toUpperCase();
  }
}
