import { ITranscriptProvider } from "./types";
import { YouTubeVideoMetadata } from "@/types/youtube";
import { NormalizedTranscript, RawTranscriptItem, TranscriptErrorCode } from "@/types/transcript";
import { normalizeTranscript, decodeHtmlEntities } from "./normalizer";
import { formatDuration } from "@/lib/utils";
import { YoutubeTranscript } from "youtube-transcript";
import { ProxyAgent, fetch as undiciFetch } from "undici";

export class TranscriptError extends Error {
  code: TranscriptErrorCode;
  suggestion?: string;
  debug?: Record<string, any>;

  constructor(code: TranscriptErrorCode, message: string, suggestion?: string, debug?: Record<string, any>) {
    super(message);
    this.name = "TranscriptError";
    this.code = code;
    this.suggestion = suggestion;
    this.debug = debug;
  }
}

/**
 * Returns a fetch function configured with proxy if YOUTUBE_PROXY or HTTPS_PROXY is present
 */
export function getCustomFetch(useProxyIfAvailable: boolean = true): typeof fetch {
  const proxyUrl =
    useProxyIfAvailable
      ? process.env.YOUTUBE_PROXY ||
        process.env.HTTPS_PROXY ||
        process.env.HTTP_PROXY ||
        process.env.PROXY_URL
      : null;

  if (proxyUrl) {
    try {
      const dispatcher = new ProxyAgent(proxyUrl);
      return ((url: any, init?: any) =>
        undiciFetch(url, {
          ...init,
          dispatcher,
          signal: init?.signal || AbortSignal.timeout(6000),
        })) as unknown as typeof fetch;
    } catch (e) {
      console.warn("[Transcript] Failed to initialize ProxyAgent:", e);
    }
  }

  return ((url: any, init?: any) =>
    fetch(url, {
      ...init,
      signal: init?.signal || AbortSignal.timeout(5000),
    })) as typeof fetch;
}

export class YouTubeTranscriptProvider implements ITranscriptProvider {
  /**
   * Fetch Video Metadata using YouTube oEmbed and Innertube API
   */
  async getVideoMetadata(videoId: string): Promise<YouTubeVideoMetadata> {
    const videoUrl = `https://www.youtube.com/watch?v=${videoId}`;
    const defaultThumbnail = `https://img.youtube.com/vi/${videoId}/maxresdefault.jpg`;
    const directFetch = getCustomFetch(false);

    let title = "YouTube Video";
    let channelName = "YouTube Creator";
    let channelUrl: string | undefined;
    let thumbnailUrl = defaultThumbnail;
    let durationSeconds = 0;

    // 1. Fetch official oEmbed data
    try {
      const oembedRes = await directFetch(
        `https://www.youtube.com/oembed?url=${encodeURIComponent(videoUrl)}&format=json`,
        {
          headers: { "User-Agent": "Mozilla/5.0 (compatible; TubeMindBot/1.0)" },
          signal: AbortSignal.timeout(3000),
        }
      );

      if (oembedRes.ok) {
        const oembed: any = await oembedRes.json();
        title = oembed.title || title;
        channelName = oembed.author_name || channelName;
        channelUrl = oembed.author_url;
        if (oembed.thumbnail_url) {
          thumbnailUrl = oembed.thumbnail_url;
        }
      }
    } catch (e) {
      // Fallback
    }

    // 2. Fetch Innertube video details
    try {
      const innertubeRes = await directFetch("https://www.youtube.com/youtubei/v1/player", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
          "X-YouTube-Client-Name": "1",
          "X-YouTube-Client-Version": "2.20240313.01.00",
        },
        body: JSON.stringify({
          context: {
            client: {
              clientName: "WEB",
              clientVersion: "2.20240313.01.00",
              hl: "en",
              gl: "US",
            },
          },
          videoId,
        }),
        signal: AbortSignal.timeout(3000),
      });

      if (innertubeRes.ok) {
        const data: any = await innertubeRes.json();
        if (data.videoDetails) {
          title = data.videoDetails.title || title;
          channelName = data.videoDetails.author || channelName;
          if (data.videoDetails.lengthSeconds) {
            durationSeconds = parseInt(data.videoDetails.lengthSeconds, 10) || 0;
          }
        }
      }
    } catch (e) {}

    return {
      videoId,
      url: videoUrl,
      title,
      channelName,
      channelUrl,
      durationSeconds,
      durationFormatted: formatDuration(durationSeconds),
      thumbnailUrl,
      hasCaptions: true,
      captionType: "auto",
      availableLanguages: [
        { code: "en", name: "English", isAutoGenerated: true },
        { code: "hi", name: "Hindi", isAutoGenerated: true },
        { code: "ur", name: "Urdu", isAutoGenerated: true },
        { code: "es", name: "Spanish", isAutoGenerated: true },
      ],
    };
  }

  async getAvailableLanguages(
    videoId: string
  ): Promise<Array<{ code: string; name: string; isAutoGenerated?: boolean }>> {
    return [
      { code: "en", name: "English", isAutoGenerated: true },
      { code: "hi", name: "Hindi", isAutoGenerated: true },
      { code: "ur", name: "Urdu", isAutoGenerated: true },
      { code: "es", name: "Spanish", isAutoGenerated: true },
      { code: "fr", name: "French", isAutoGenerated: true },
      { code: "de", name: "German", isAutoGenerated: true },
    ];
  }

  /**
   * Primary transcript retriever with Multi-Tier Fast Fallback:
   * Tier 1: Direct YoutubeTranscript Library
   * Tier 2: Direct InnerTube (Android/iOS/Web clients)
   * Tier 3: Direct Webpage HTML extraction
   * Tier 4: Proxy-based extraction (if proxy configured)
   * Tier 5: RapidAPI YouTube Transcript API (if configured)
   * Tier 6: Groq Whisper AI Speech-to-Text Fallback
   */
  async getTranscript(videoId: string, languageCode?: string): Promise<NormalizedTranscript> {
    let rawItems: RawTranscriptItem[] = [];
    let detectedLang = languageCode || "en";
    const traces: string[] = [];

    // ----------------------------------------------------
    // Tier 1: Direct YoutubeTranscript Library
    // ----------------------------------------------------
    try {
      const transcriptData = await YoutubeTranscript.fetchTranscript(videoId, {
        ...(languageCode && languageCode !== "auto" ? { lang: languageCode } : {}),
      });

      if (transcriptData && transcriptData.length > 0) {
        rawItems = transcriptData.map((item) => ({
          text: item.text,
          duration: item.duration,
          offset: item.offset,
          lang: item.lang || languageCode || "en",
        }));
        detectedLang = transcriptData[0]?.lang || languageCode || "en";
        traces.push("Tier 1 (YoutubeTranscript Direct): SUCCESS");
      } else {
        traces.push("Tier 1 (YoutubeTranscript Direct): Empty items");
      }
    } catch (err: any) {
      traces.push(`Tier 1 (YoutubeTranscript Direct): ${err?.message || "Failed"}`);
    }

    // ----------------------------------------------------
    // Tier 2: Direct InnerTube (Android / iOS / Web)
    // ----------------------------------------------------
    if (rawItems.length === 0) {
      try {
        const directFetch = getCustomFetch(false);
        const innerTubeItems = await this.fetchFromInnerTubeDirect(videoId, languageCode, directFetch);
        if (innerTubeItems && innerTubeItems.items.length > 0) {
          rawItems = innerTubeItems.items;
          detectedLang = innerTubeItems.lang;
          traces.push("Tier 2 (Direct InnerTube): SUCCESS");
        } else {
          traces.push("Tier 2 (Direct InnerTube): No tracks returned");
        }
      } catch (e: any) {
        traces.push(`Tier 2 (Direct InnerTube): ${e?.message || "Failed"}`);
      }
    }

    // ----------------------------------------------------
    // Tier 3: Direct Webpage HTML extraction
    // ----------------------------------------------------
    if (rawItems.length === 0) {
      try {
        const directFetch = getCustomFetch(false);
        const htmlItems = await this.fetchFromWebPageDirect(videoId, languageCode, directFetch);
        if (htmlItems && htmlItems.items.length > 0) {
          rawItems = htmlItems.items;
          detectedLang = htmlItems.lang;
          traces.push("Tier 3 (WebPage HTML): SUCCESS");
        } else {
          traces.push("Tier 3 (WebPage HTML): No tracks returned");
        }
      } catch (htmlErr: any) {
        traces.push(`Tier 3 (WebPage HTML): ${htmlErr?.message || "Failed"}`);
      }
    }

    // ----------------------------------------------------
    // Tier 4: Proxy InnerTube (If proxy configured)
    // ----------------------------------------------------
    const hasProxy = Boolean(process.env.YOUTUBE_PROXY || process.env.HTTPS_PROXY);
    if (rawItems.length === 0 && hasProxy) {
      try {
        const proxyFetch = getCustomFetch(true);
        const proxyItems = await this.fetchFromInnerTubeDirect(videoId, languageCode, proxyFetch);
        if (proxyItems && proxyItems.items.length > 0) {
          rawItems = proxyItems.items;
          detectedLang = proxyItems.lang;
          traces.push("Tier 4 (Proxy InnerTube): SUCCESS");
        } else {
          traces.push("Tier 4 (Proxy InnerTube): No tracks returned");
        }
      } catch (proxyErr: any) {
        traces.push(`Tier 4 (Proxy InnerTube): ${proxyErr?.message || "Failed"}`);
      }
    }

    // ----------------------------------------------------
    // Tier 5: RapidAPI YouTube Transcript API Fallback
    // ----------------------------------------------------
    if (rawItems.length === 0) {
      const rapidApiKey = process.env.RAPIDAPI_KEY || process.env.YOUTUBE_API_KEY;
      if (rapidApiKey) {
        try {
          const rapidItems = await this.fetchFromRapidApi(videoId, languageCode, rapidApiKey);
          if (rapidItems && rapidItems.items.length > 0) {
            rawItems = rapidItems.items;
            detectedLang = rapidItems.lang;
            traces.push("Tier 5 (RapidAPI): SUCCESS");
          } else {
            traces.push("Tier 5 (RapidAPI): Empty response");
          }
        } catch (rapidErr: any) {
          traces.push(`Tier 5 (RapidAPI): ${rapidErr?.message || "Failed"}`);
        }
      }
    }

    // If any caption fetcher succeeded, normalize and return immediately
    if (rawItems && rawItems.length > 0) {
      return normalizeTranscript(
        rawItems,
        videoId,
        detectedLang,
        this.getLanguageName(detectedLang),
        true
      );
    }

    // ----------------------------------------------------
    // Tier 6: Groq Whisper AI Fallback
    // ----------------------------------------------------
    const hasGroqKey = Boolean(process.env.GROQ_API_KEY || process.env.STT_API_KEY);
    if (hasGroqKey) {
      try {
        console.log("[Transcript Tier 6] Engaging Groq Whisper AI Speech-to-Text fallback...");
        const { SpeechToTextFallbackProvider } = await import("./speech-to-text-provider");
        const sttProvider = new SpeechToTextFallbackProvider();
        const result = await sttProvider.transcribeVideo(videoId, languageCode);
        traces.push("Tier 6 (Groq STT): SUCCESS");
        return result;
      } catch (sttErr: any) {
        traces.push(`Tier 6 (Groq STT): ${sttErr?.message || "Failed"}`);
        console.error("[Transcript Tier 6] Groq Whisper fallback error:", sttErr?.message || sttErr);
      }
    } else {
      traces.push("Tier 6 (Groq STT): SKIPPED (GROQ_API_KEY not configured in environment)");
    }

    // ----------------------------------------------------
    // If all tiers failed, provide a helpful actionable error
    // ----------------------------------------------------
    const isDatacenterIpBlock = !hasProxy && !hasGroqKey;
    const suggestion = isDatacenterIpBlock
      ? "YouTube blocks serverless cloud IPs (Vercel). Please add GROQ_API_KEY or YOUTUBE_PROXY in your Vercel Environment Variables to bypass this block."
      : "Try another video with closed captions or spoken audio enabled.";

    throw new TranscriptError(
      "CAPTIONS_DISABLED",
      "Transcripts or captions are currently unavailable for this video.",
      suggestion,
      {
        hasGroqKey,
        hasProxy,
        hasRapidApiKey: Boolean(process.env.RAPIDAPI_KEY || process.env.YOUTUBE_API_KEY),
        traces,
      }
    );
  }

  /**
   * Directly queries InnerTube with multiple client headers (Android, iOS, Web) and parses TimedText XML
   */
  private async fetchFromInnerTubeDirect(
    videoId: string,
    requestedLang: string | undefined,
    customFetch: typeof fetch
  ): Promise<{ items: RawTranscriptItem[]; lang: string } | null> {
    const clients = [
      {
        clientName: "ANDROID",
        clientVersion: "20.10.38",
        userAgent: "com.google.android.youtube/20.10.38 (Linux; U; Android 14)",
      },
      {
        clientName: "IOS",
        clientVersion: "19.45.4",
        userAgent: "com.google.ios.youtube/19.45.4 (iPhone16,2; U; CPU OS 17_5_1 like Mac OS X)",
      },
      {
        clientName: "WEB",
        clientVersion: "2.20240313.01.00",
        userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
      },
    ];

    for (const client of clients) {
      try {
        const response = await customFetch("https://www.youtube.com/youtubei/v1/player?prettyPrint=false", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "User-Agent": client.userAgent,
          },
          body: JSON.stringify({
            context: {
              client: {
                clientName: client.clientName,
                clientVersion: client.clientVersion,
                hl: requestedLang && requestedLang !== "auto" ? requestedLang : "en",
                gl: "US",
              },
            },
            videoId,
          }),
          signal: AbortSignal.timeout(4000),
        });

        if (!response.ok) continue;

        const data: any = await response.json();
        const captionTracks: any[] = data?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
        if (!Array.isArray(captionTracks) || captionTracks.length === 0) {
          continue;
        }

        // Find track matching requested language or pick the first available
        let selectedTrack = captionTracks[0];
        if (requestedLang && requestedLang !== "auto") {
          const match = captionTracks.find((t) => t.languageCode === requestedLang);
          if (match) selectedTrack = match;
        }

        if (!selectedTrack?.baseUrl) continue;

        // Fetch TimedText XML with browser headers
        const captionRes = await customFetch(selectedTrack.baseUrl, {
          headers: {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
            "Accept": "*/*",
            "Accept-Language": "en-US,en;q=0.9",
          },
          signal: AbortSignal.timeout(4000),
        });

        if (!captionRes.ok) continue;

        const xml = await captionRes.text();
        const items = this.parseTimedTextXml(xml, selectedTrack.languageCode || "en");

        if (items.length > 0) {
          return { items, lang: selectedTrack.languageCode || "en" };
        }
      } catch (e) {
        // Try next client
      }
    }

    return null;
  }

  /**
   * Scrapes webpage HTML directly for ytInitialPlayerResponse
   */
  private async fetchFromWebPageDirect(
    videoId: string,
    requestedLang: string | undefined,
    customFetch: typeof fetch
  ): Promise<{ items: RawTranscriptItem[]; lang: string } | null> {
    try {
      const url = `https://www.youtube.com/watch?v=${videoId}`;
      const res = await customFetch(url, {
        headers: {
          "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
          "Accept-Language": requestedLang && requestedLang !== "auto" ? requestedLang : "en-US,en;q=0.9",
          "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        },
        signal: AbortSignal.timeout(5000),
      });

      if (!res.ok) return null;
      const html = await res.text();

      const startToken = "var ytInitialPlayerResponse = ";
      const idx = html.indexOf(startToken);
      if (idx === -1) return null;

      const jsonStart = idx + startToken.length;
      let depth = 0;
      let jsonEnd = -1;
      for (let i = jsonStart; i < html.length; i++) {
        if (html[i] === "{") depth++;
        else if (html[i] === "}") {
          depth--;
          if (depth === 0) {
            jsonEnd = i + 1;
            break;
          }
        }
      }

      if (jsonEnd === -1) return null;
      const data = JSON.parse(html.slice(jsonStart, jsonEnd));
      const captionTracks: any[] = data?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
      if (!Array.isArray(captionTracks) || captionTracks.length === 0) return null;

      let selectedTrack = captionTracks[0];
      if (requestedLang && requestedLang !== "auto") {
        const match = captionTracks.find((t) => t.languageCode === requestedLang);
        if (match) selectedTrack = match;
      }

      if (!selectedTrack?.baseUrl) return null;

      const captionRes = await customFetch(selectedTrack.baseUrl, {
        headers: {
          "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
          "Accept": "*/*",
        },
        signal: AbortSignal.timeout(4000),
      });

      if (!captionRes.ok) return null;
      const xml = await captionRes.text();
      const items = this.parseTimedTextXml(xml, selectedTrack.languageCode || "en");

      if (items.length > 0) {
        return { items, lang: selectedTrack.languageCode || "en" };
      }
    } catch (e) {}

    return null;
  }

  /**
   * Parse TimedText XML supporting both srv3 format (<p t="ms" d="ms">) and classic format (<text start="s" dur="s">)
   */
  private parseTimedTextXml(xml: string, lang: string): RawTranscriptItem[] {
    const items: RawTranscriptItem[] = [];

    // Format 1: srv3 (<p t="ms" d="ms"><s>word</s></p>)
    const pRegex = /<p\s+t="(\d+)"\s+d="(\d+)"[^>]*>([\s\S]*?)<\/p>/g;
    let match;
    while ((match = pRegex.exec(xml)) !== null) {
      const startMs = parseInt(match[1], 10);
      const durMs = parseInt(match[2], 10);
      const inner = match[3];

      let text = "";
      const sRegex = /<s[^>]*>([^<]*)<\/s>/g;
      let sMatch;
      while ((sMatch = sRegex.exec(inner)) !== null) {
        text += sMatch[1];
      }
      if (!text) {
        text = inner.replace(/<[^>]+>/g, "");
      }
      text = decodeHtmlEntities(text).trim();

      if (text) {
        items.push({
          text,
          offset: startMs,
          duration: durMs,
          lang,
        });
      }
    }

    if (items.length > 0) return items;

    // Format 2: Classic (<text start="12.34" dur="5.67">Content</text>)
    const textRegex = /<text\s+start="([\d.]+)"\s+dur="([\d.]+)"[^>]*>([^<]*)<\/text>/g;
    while ((match = textRegex.exec(xml)) !== null) {
      const startSec = parseFloat(match[1]);
      const durSec = parseFloat(match[2]);
      const content = decodeHtmlEntities(match[3]).trim();

      if (content) {
        items.push({
          text: content,
          offset: Math.round(startSec * 1000),
          duration: Math.round(durSec * 1000),
          lang,
        });
      }
    }

    return items;
  }

  /**
   * RapidAPI YouTube Transcript API Fallback
   */
  private async fetchFromRapidApi(
    videoId: string,
    languageCode: string | undefined,
    apiKey: string
  ): Promise<{ items: RawTranscriptItem[]; lang: string } | null> {
    try {
      const url = `https://youtube-transcriptor.p.rapidapi.com/transcript?video_id=${videoId}&lang=${languageCode || "en"}`;
      const res = await fetch(url, {
        headers: {
          "x-rapidapi-key": apiKey,
          "x-rapidapi-host": "youtube-transcriptor.p.rapidapi.com",
        },
        signal: AbortSignal.timeout(4000),
      });

      if (res.ok) {
        const data = await res.json();
        if (Array.isArray(data) && data.length > 0) {
          const items: RawTranscriptItem[] = data.map((d: any) => ({
            text: d.text || d.subtitle || "",
            offset: typeof d.start === "number" ? Math.round(d.start * 1000) : (d.offset || 0),
            duration: typeof d.duration === "number" ? Math.round(d.duration * 1000) : (d.duration || 2500),
            lang: languageCode || "en",
          }));
          return { items, lang: languageCode || "en" };
        }
      }
    } catch (e) {
      // RapidAPI fallback failed
    }
    return null;
  }

  private getLanguageName(code: string): string {
    const map: Record<string, string> = {
      en: "English",
      hi: "Hindi",
      ur: "Urdu",
      es: "Spanish",
      fr: "French",
      de: "German",
      ar: "Arabic",
      pt: "Portuguese",
      ja: "Japanese",
      zh: "Chinese",
    };
    return map[code.toLowerCase()] || code.toUpperCase();
  }
}
