export interface TranscriptSegment {
  index: number;
  startTime: number;      // in seconds
  duration: number;       // in seconds
  endTime: number;        // in seconds
  startFormatted: string; // e.g. "01:24" or "01:04:22"
  endFormatted: string;   // e.g. "01:28"
  text: string;
}

export interface RawTranscriptItem {
  text: string;
  duration: number;
  offset: number;
  lang?: string;
}

export interface NormalizedTranscript {
  videoId: string;
  language: string;
  languageName: string;
  isAutoGenerated: boolean;
  totalSegments: number;
  totalDurationSeconds: number;
  totalWords: number;
  segments: TranscriptSegment[];
  fullText: string;
  cleanText: string;
}

export type SubtitleFormat = "srt" | "vtt" | "txt" | "json" | "markdown";

export type TranscriptErrorCode =
  | "INVALID_URL"
  | "VIDEO_NOT_FOUND"
  | "TRANSCRIPT_NOT_AVAILABLE"
  | "CAPTIONS_DISABLED"
  | "PRIVATE_OR_AGE_RESTRICTED"
  | "RATE_LIMITED"
  | "TIMEOUT"
  | "INTERNAL_ERROR";

export interface TranscriptErrorResponse {
  error: true;
  code: TranscriptErrorCode;
  message: string;
  suggestion?: string;
}
