export interface YouTubeVideoMetadata {
  videoId: string;
  url: string;
  title: string;
  channelName: string;
  channelUrl?: string;
  durationSeconds: number;
  durationFormatted: string;
  thumbnailUrl: string;
  viewCount?: number;
  publishDate?: string;
  description?: string;
  hasCaptions: boolean;
  captionType?: "manual" | "asr" | "auto" | "none";
  availableLanguages: Array<{
    code: string;
    name: string;
    isAutoGenerated?: boolean;
  }>;
}

export interface ParsedYouTubeUrl {
  isValid: boolean;
  videoId: string | null;
  timestamp?: number | null;
  normalizedUrl: string | null;
  sourceType: "standard" | "shorts" | "embed" | "shortlink" | "unknown";
}
