"use client";

import React, { useState, useEffect, useRef, useMemo } from "react";
import { Search, ChevronUp, ChevronDown, Copy, Check, Globe, Play, Sparkles } from "lucide-react";
import { NormalizedTranscript, TranscriptSegment } from "@/types/transcript";
import { TOP_LANGUAGES } from "@/types/persona";

interface TranscriptViewerProps {
  transcript: NormalizedTranscript;
  availableLanguages?: Array<{ code: string; name: string; isAutoGenerated?: boolean }>;
  currentLanguage: string;
  onLanguageChange: (langCode: string) => void;
  onSeek: (seconds: number) => void;
}

export function TranscriptViewer({
  transcript,
  availableLanguages = [],
  currentLanguage,
  onLanguageChange,
  onSeek,
}: TranscriptViewerProps) {
  const [searchQuery, setSearchQuery] = useState("");
  const [activeMatchIndex, setActiveMatchIndex] = useState(0);
  const [copied, setCopied] = useState(false);
  const searchInputRef = useRef<HTMLInputElement>(null);
  const segmentsContainerRef = useRef<HTMLDivElement>(null);

  // Combine top curated languages with video's detected languages
  const combinedLanguages = useMemo(() => {
    const list: Array<{ code: string; name: string; isAutoGenerated?: boolean }> = [];
    const addedCodes = new Set<string>();

    // 1. Add video's specific available tracks first
    availableLanguages.forEach((l) => {
      if (!addedCodes.has(l.code)) {
        addedCodes.add(l.code);
        list.push(l);
      }
    });

    // 2. Add Top global languages (English, Urdu, Hindi, Arabic, Spanish, French, German)
    TOP_LANGUAGES.forEach((top) => {
      if (!addedCodes.has(top.code)) {
        addedCodes.add(top.code);
        list.push({
          code: top.code,
          name: `${top.flag} ${top.name} (${top.nativeName})`,
          isAutoGenerated: true,
        });
      }
    });

    return list;
  }, [availableLanguages]);

  // Keyboard shortcut listener: Cmd/Ctrl + F
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === "f") {
        e.preventDefault();
        searchInputRef.current?.focus();
        searchInputRef.current?.select();
      }
    };
    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, []);

  // Filter & match calculation
  const matchingSegmentIndices = useMemo(() => {
    if (!searchQuery.trim()) return [];
    const query = searchQuery.toLowerCase().trim();
    const indices: number[] = [];

    transcript.segments.forEach((seg, idx) => {
      if (seg.text.toLowerCase().includes(query)) {
        indices.push(idx);
      }
    });

    return indices;
  }, [searchQuery, transcript.segments]);

  useEffect(() => {
    setActiveMatchIndex(0);
  }, [searchQuery]);

  const handleNextMatch = () => {
    if (matchingSegmentIndices.length === 0) return;
    const nextIdx = (activeMatchIndex + 1) % matchingSegmentIndices.length;
    setActiveMatchIndex(nextIdx);
    scrollToSegment(matchingSegmentIndices[nextIdx]);
  };

  const handlePrevMatch = () => {
    if (matchingSegmentIndices.length === 0) return;
    const prevIdx =
      (activeMatchIndex - 1 + matchingSegmentIndices.length) % matchingSegmentIndices.length;
    setActiveMatchIndex(prevIdx);
    scrollToSegment(matchingSegmentIndices[prevIdx]);
  };

  const scrollToSegment = (segIdx: number) => {
    const el = document.getElementById(`segment-${segIdx}`);
    if (el && segmentsContainerRef.current) {
      el.scrollIntoView({ behavior: "smooth", block: "center" });
    }
  };

  const handleCopyAll = async () => {
    try {
      await navigator.clipboard.writeText(transcript.cleanText || transcript.fullText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Clipboard copy failed:", err);
    }
  };

  const renderHighlightedText = (text: string, isMatch: boolean, isCurrentActiveMatch: boolean) => {
    if (!searchQuery.trim() || !text.toLowerCase().includes(searchQuery.toLowerCase())) {
      return text;
    }

    const regex = new RegExp(`(${searchQuery.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")})`, "gi");
    const parts = text.split(regex);

    return parts.map((part, i) =>
      part.toLowerCase() === searchQuery.toLowerCase() ? (
        <mark
          key={i}
          className={`transcript-highlight ${isCurrentActiveMatch ? "active" : ""}`}
        >
          {part}
        </mark>
      ) : (
        part
      )
    );
  };

  return (
    <div className="flex flex-col h-full bg-card rounded-2xl border border-border shadow-md overflow-hidden">
      {/* Header Toolbar */}
      <div className="p-3.5 border-b border-border bg-secondary/30 flex flex-wrap items-center justify-between gap-2.5">
        <div className="flex items-center gap-2">
          <span className="text-xs font-bold uppercase tracking-wider text-foreground flex items-center gap-1.5">
            <span className="w-2 h-2 rounded-full bg-brand-500 animate-pulse" />
            Transcript ({transcript.totalSegments} segments)
          </span>
        </div>

        {/* Language selector including Urdu, Hindi, Arabic, Spanish, French, German */}
        <div className="flex items-center gap-2">
          <div className="flex items-center gap-1 bg-background border border-border rounded-lg px-2 py-1 text-xs">
            <Globe className="w-3.5 h-3.5 text-muted-foreground" />
            <select
              value={currentLanguage}
              onChange={(e) => onLanguageChange(e.target.value)}
              className="bg-transparent text-foreground focus:outline-none cursor-pointer text-xs font-semibold"
            >
              {combinedLanguages.map((lang) => (
                <option key={lang.code} value={lang.code} className="bg-card text-foreground">
                  {lang.name}
                </option>
              ))}
            </select>
          </div>

          <button
            onClick={handleCopyAll}
            className="flex items-center gap-1.5 px-2.5 py-1 text-xs font-medium bg-background hover:bg-secondary border border-border text-foreground rounded-lg transition-all"
            title="Copy Full Transcript"
          >
            {copied ? (
              <>
                <Check className="w-3.5 h-3.5 text-emerald-500" />
                <span className="text-emerald-500">Copied</span>
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5 text-muted-foreground" />
                <span>Copy</span>
              </>
            )}
          </button>
        </div>
      </div>

      {/* Search Bar */}
      <div className="p-3 border-b border-border bg-background flex items-center gap-2">
        <div className="relative flex-1 flex items-center">
          <Search className="w-4 h-4 absolute left-3 text-muted-foreground pointer-events-none" />
          <input
            ref={searchInputRef}
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search transcript (Cmd/Ctrl + F)..."
            className="w-full pl-9 pr-8 py-1.5 text-xs bg-secondary/60 text-foreground rounded-lg border border-transparent focus:border-brand-500 focus:bg-background focus:outline-none transition-all placeholder:text-muted-foreground/60"
          />
          {searchQuery && (
            <button
              onClick={() => setSearchQuery("")}
              className="absolute right-2.5 text-xs text-muted-foreground hover:text-foreground"
            >
              ✕
            </button>
          )}
        </div>

        {/* Search Results Navigation */}
        {searchQuery.trim() && (
          <div className="flex items-center gap-1 text-xs text-muted-foreground whitespace-nowrap">
            <span>
              {matchingSegmentIndices.length > 0
                ? `${activeMatchIndex + 1}/${matchingSegmentIndices.length}`
                : "0 matches"}
            </span>
            <button
              onClick={handlePrevMatch}
              disabled={matchingSegmentIndices.length === 0}
              className="p-1 rounded hover:bg-secondary disabled:opacity-40"
              title="Previous match"
            >
              <ChevronUp className="w-3.5 h-3.5" />
            </button>
            <button
              onClick={handleNextMatch}
              disabled={matchingSegmentIndices.length === 0}
              className="p-1 rounded hover:bg-secondary disabled:opacity-40"
              title="Next match"
            >
              <ChevronDown className="w-3.5 h-3.5" />
            </button>
          </div>
        )}
      </div>

      {/* Segments List */}
      <div
        ref={segmentsContainerRef}
        className="flex-1 overflow-y-auto p-4 space-y-2.5 max-h-[500px] lg:max-h-[640px] text-sm"
      >
        {transcript.segments.map((seg, idx) => {
          const isMatched = matchingSegmentIndices.includes(idx);
          const isCurrentActive =
            matchingSegmentIndices.length > 0 &&
            matchingSegmentIndices[activeMatchIndex] === idx;

          return (
            <div
              key={seg.index}
              id={`segment-${idx}`}
              className={`p-2.5 rounded-xl transition-all flex items-start gap-3 group hover:bg-secondary/60 border ${
                isCurrentActive
                  ? "bg-brand-500/10 border-brand-500/30"
                  : isMatched
                  ? "bg-amber-500/5 border-amber-500/20"
                  : "border-transparent"
              }`}
            >
              {/* Clickable timestamp seek badge */}
              <button
                onClick={() => onSeek(seg.startTime)}
                className="flex-shrink-0 px-2 py-0.5 rounded-md font-mono text-xs font-semibold bg-secondary text-brand-600 dark:text-brand-400 hover:bg-brand-600 hover:text-white transition-colors flex items-center gap-1 group-hover:shadow-sm"
                title={`Seek video to ${seg.startFormatted}`}
              >
                <Play className="w-2.5 h-2.5 fill-current" />
                <span>{seg.startFormatted}</span>
              </button>

              {/* Text */}
              <p className="text-foreground text-sm leading-relaxed flex-1">
                {renderHighlightedText(seg.text, isMatched, isCurrentActive)}
              </p>
            </div>
          );
        })}
      </div>
    </div>
  );
}
